### ISSUE TITLE
23 problems for 2/14 Maine ONR Study >#10

### ISSUE THREAD

**Issue by perspegrity5** [perspegrity5/UMassONRMathTutorsContent#1]
8 Formality problems to be converted to HTML (should be done by Feb 6
15 Flash problems - done and tested by DM; 
(assistment links not tested yet)

Problems listed here:
https://docs.google.com/spreadsheet/ccc?key=0AsaG9e7moczwdGJMTndSUTdtaFBVQ05TTmhWaUVnblE&usp=drive_web#gid=3

**Comment by lynn99** [comment]
The eight Formality problems have been converted to HTML and are ready for the Word Problem Author (Minghui) and to be uploaded (Lynn and David).
See Issue #10

**Comment by perspegrity5** [comment]
Danielle tested example mode and found several issues, see
https://docs.google.com/spreadsheet/ccc?key=0AhVf9gPh-HMNdHduNHc0cFRwUUY0aHBRTXVrVzdEQVE&usp=sharing

**Comment by minghuitai** [comment]
I did not record hint audio for problem 846 and 847.
(Other formality problems with the same issue might be possible that Kevin 
did not record audio for hint. Could check Edge files and see if there is audio for hint.)

**Comment by lynn99** [comment]
David is not going to be at the meeting today.  He and Jess are going to meet with Melissa at that time.

Maybe you and/or I should check in with him and see whether any of these are actual issues or are simply the way the problems are supposed to behave in Example mode?

L

**Comment by lynn99** [comment]
Thanks!  As I suspected.

L
