### ISSUE TITLE
Adding prerequisites to MathSpring

### ISSUE THREAD

**Issue by perspegrity5** [perspegrity5/UMassONRMathTutorsContent#18]
using the prerequisite network from Zimba
- add to the database
- implement topic/standard sequencing rules for using prerequisites
- test and refine

**Comment by IvonArroyo** [comment]
We should talk about how this will work, as I still cannot picture it. I cannot see how this is compatible with the topics that have been selected for the teacher, topics will pop-up in the progress page on the fly for individual students? Does this mean that different students will have different topics in their SPP even though they are in the same class? 

Maybe I can bring a PPT to the next meeting about what are several issues why I am doubtful about this.
