### ISSUE TITLE
problem_267 HTML buttons not working

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#22]
While running mathspring this problem's buttons do not respond to clicks.

**Comment by lynn99** [comment]
I have this as ready for live testing but not ready to be taken live.

My note says specifically to check whether the sound files play and answer buttons work before it is taken live.  

This is one of those created in a template and then brought forward. Disappointing to hear that the buttons don’t work.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
Scientific Reasoning Research Institute
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
Ah, I do show that it had been enabled but that it needed testing.

The rest in the list at this link were disabled last I checked and should be disabled now.

https://docs.google.com/document/d/1BRIaMezwJvfuewpyyBsZxI853WIglZqxsd0kp7_V_TM/edit

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
Scientific Reasoning Research Institute
University of Massachusetts—Amherst
(413) 230-4634
