### ISSUE TITLE
problem ID 13 has buttons unconverted

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#29]
This problem is marked 'ready' and is showing up even though it does not have its buttons converted.
I'm turning it OFF so I don't keep seeing it.   Please leave it off until it is fixed, replaced with HTML, or until we decide we don't need it at all and then it should be deleted.

**Comment by lynn99** [comment]
Can you set it to testable so that we can create an HTML version?

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634
