### ISSUE TITLE
Problem_297 (HTML) incorrect file name

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#30]
The filename in the db says it should be problem_297.html

What is stored in the directory in apache is HTML 297.html.   Note other support files (js)  also have
incorrect names so that linkage between the HTML and the JS will be broken if filenames are just changed without correcting it in Edge.    

Note this is content marked testable,  but when it is this broken,   it causes blowouts in the tutor that lead one to believe that something major is wrong.

**Comment by lynn99** [comment]
You are correct, it is misnamed.  I can put it into the Check folder for someone to rename.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
I have put this problem in the BACK and FORTH Google docs folder for Minghui to repair.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by minghuitai** [comment]
Fixed.

Minghui

**Comment by lynn99** [comment]
Problem_297 should be disabled until the repaired version is uploaded to Git and to the server.
Tom, it has not yet made it back to your Upload folder.

**Comment by minghuitai** [comment]
I have fixed problem 297.
Let me know if it works fine.

Minghui

**Comment by lynn99** [comment]
Yes Minghui,

You have fixed it but the fixed version has not been uploaded so they won’t be able to check it.  I can check it and then give it to Tom to upload.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
Hi Lynn,

(Back from Boulder (3:30 last night!).  I had a private meeting with Ken Wilber! Tell you about it later.)

RE 297: so I should wait until it a goes into Ready To Commit?
there are 5 problems in there now. Should I upload?  We are in the middle of modifying the systems and I'm not sure about the states yet.

Now in "ready for Prob AUthor" is "problem_267 tweak MT"  
should I take action on this one?

On Sep 30, 2014, at 7:33 PM, lynn99 notifications@github.com wrote:

> Yes Minghui, 
> 
> You have fixed it but the fixed version has not been uploaded so they won’t be able to check it. I can check it and then give it to Tom to upload. 
> 
> — 
> Lynn Stephens 
> Post Doctoral Researcher 
> School of Computer Science and 
> College of Education 
> University of Massachusetts—Amherst 
> (413) 230-4634 
> 
> On Sep 30, 2014, at 7:27 PM, minghuitai notifications@github.com wrote: 
> 
> > I have fixed problem 297. 
> > Let me know if it works fine. 
> > 
> > Minghui 
> > 
> > ---
> > 
> > From: lynn99 notifications@github.com 
> > To: tmuray/UMassONRMathTutorsContent UMassONRMathTutorsContent@noreply.github.com 
> > Cc: minghuitai minghui_tai@yahoo.com 
> > Sent: Tuesday, September 30, 2014 7:12 PM 
> > Subject: Re: [UMassONRMathTutorsContent] Problem_297 (HTML) incorrect file name (#30) 
> > 
> > Problem_297 should be disabled until the repaired version is uploaded to Git and to the server. 
> > Tom, it has not yet made it back to your Upload folder. 
> > — 
> > Reply to this email directly or view it on GitHub. 
> > — 
> > Reply to this email directly or view it on GitHub. 
> > 
> > —
> > Reply to this email directly or view it on GitHub.

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 

University of Massachusetts Amherst

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

http://www.tommurray.us (also tommurray.us@gmail.com)

**Comment by lynn99** [comment]
Hi Tom,

Anything in Ready for Problem Author is ready for both problem author and upload to Git and to server.
The 5 problems in the Read to Commit folder are ready to be uploaded.  They should be fine in problem author.

Yes, 297 should wait until it goes into Ready to Commit.

This points out a gap in our documentation process.  Once problems go into folder ‘3 HTML5 problems uploaded and ready for live testing” and those problems fail—what then?

I think they need to be changed to DISABLED immediately and their folder within ‘3 HTML5… “ should be annotated to reflect this.

I will change the 297 folder label now to show you what I mean.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
Actually I did already have a procedure for that, just an incomplete one.

In "3 HTML5 problems uploaded and ready for live testing”  all the folders that end in ‘replace’ are problems that failed the Testable test and are being repaired or have already been repaired and are waiting in your Ready to Commit folder.

What is missing is that the problems that failed were not disabled.  They were left as Testable.  I was thinking that would not be an issue, but it is.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
So if we start disabling all problems that fail the Testable test (testing from My Progress Page), this means that all problems in your Ready to Upload folder will also require you to change them from Disabled to Testable.

Does that mean that you would be going into the Word Problem Author for them?  If that is so, then you really do need only one folder because all problems in that folder will require Git commit, Upload to server, and Word Problem Author.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634
