### ISSUE TITLE
problem ID 539  problem_574 buttons not converted

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#31]
I'm turning this problem off.   Its a bad Flash problem

**Comment by lynn99** [comment]
Can you set it to testable so that we can see it to recreate it?

Or would you prefer me to do that at the time we are ready for it?

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634
