### ISSUE TITLE
problem 20 has broken buttons

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#32]
Found another problem ID =20 that is marked ready but has bad buttons.    I'm turning it off.

I'm find this to be very suspicious that I keep finding broken Flash content marked ready.    I've hit at least 3 problems in the last couple weeks.   Every problem in the system was checked last winter.  I turned off all problems that were not working.   Now they are back on.   It's starting to seem like someone is using a process to set the status of problems and is making errors.

**Comment by perspegrity5** [comment]
Hi Dave,

(I'm back from several days in Boulder.)  Is there a backup of the database from previously that we can check against?  I have some backups but not sure what the right time frame would be to compare with.
Its certainly possible that I made an error in setting something.  

On Sep 30, 2014, at 6:54 PM, marshall62 notifications@github.com wrote:

> Found another problem ID =20 that is marked ready but has bad buttons. I'm turning it off.
> 
> I'm find this to be very suspicious that I keep finding broken Flash content marked ready. I've hit at least 3 problems in the last couple weeks. Every problem in the system was checked last winter. I turned off all problems that were not working. Now they are back on. It's starting to seem like someone is using a process to set the status of problems and is making errors.
> 
> —
> Reply to this email directly or view it on GitHub.

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 

University of Massachusetts Amherst

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

http://www.tommurray.us (also tommurray.us@gmail.com)

**Comment by marshall62** [comment]
Hi Tom:

On rose there is a folder with all the backups of the rose databases
/mnt/bck1//mysql_bck/

Each file contains several databases, so when you pick the backup you want,
you'll then need to open the file in a text editor (emacs is best because
it can handle a large file without taking a long time whereas other text
editors hang until the whole file is loaded) and copy out just the
wayangoutpostdb   database and then work with that (in Filemaker?).
