### ISSUE TITLE
5 HTML problems that should be disabled

### ISSUE THREAD

**Issue by lynn99** [perspegrity5/UMassONRMathTutorsContent#33]
These problems either failed the Testable test and are being repaired or they were never created in the first place and should never have been set to testable.  (I sent an email so this may have been resolved.)

problem_390 
problem_379
problem_381 (is not in the database yet, should never have been set to testable)
problem_388 (is not in the database yet, should never have been set to testable)
problem_439

**Comment by perspegrity5** [comment]
these have all been set to disabled or "HTML Stub".
