### ISSUE TITLE
4mality - HTML problems need re-testing

### ISSUE THREAD

**Issue by lynn99** [perspegrity5/UMassONRMathTutorsContent#34]
When I tested one of the 4mality conversions with David's new test button, there was 1) echoing in the sound and 2) the hint button played the answer hint along with the other hints.  We may need to reinsert the sound in these problems and update the template.  I suggest having the following problems reset to Testable and assigning them to Danielle or Minghui to check issues 1) and 2).

problem_838 through problem_852

**Comment by perspegrity5** [comment]
this has been moved to CMS Test Batch.
