### ISSUE TITLE
22 HTML problems for ONR--if i click on example then done the problem disappears

### ISSUE THREAD

**Issue by lynn99** [perspegrity5/UMassONRMathTutorsContent#39]
Danielle has noted this issue for all HTML problems she tested for ONR.  If she clicks on Example, then clicks Done to put the example away, the original problem disappears and she never has a chance to work it.

HTML problems make up about a third of the ONR list.  Does this issue mean that we can't use them?

**Comment by perspegrity5** [comment]
Lynn, I have this at
https://github.com/marshall62/mathspring/issues/132

we may be duplicating here :-)

On Oct 19, 2014, at 9:26 PM, lynn99 notifications@github.com wrote:

> Danielle has noted this issue for all HTML problems she tested for ONR. If she clicks on Example, then clicks Done to put the example away, the original problem disappears and she never has a chance to work it.
> 
> HTML problems make up about a third of the ONR list. Does this issue mean that we can't use them?
> 
> —
> Reply to this email directly or view it on GitHub.

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 

University of Massachusetts Amherst

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

http://www.tommurray.us (also tommurray.us@gmail.com)

**Comment by lynn99** [comment]
Oops, I looked for it just now and did not find it in the issues.

Guess I need more help using Git Hub.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
there is one github repository for content issuses and another for programmer stuff.  do you have access to both??

https://github.com/marshall62/mathspring/issues

https://github.com/tmuray/UMassONRMathTutorsContent/issues

On Oct 19, 2014, at 9:39 PM, lynn99 notifications@github.com wrote:

> Oops, I looked for it just now and did not find it in the issues. 
> 
> Guess I need more help using Git Hub. 
> 
> — 
> Lynn Stephens 
> Post Doctoral Researcher 
> School of Computer Science and 
> College of Education 
> University of Massachusetts—Amherst 
> (413) 230-4634 
> 
> On Oct 19, 2014, at 9:36 PM, tmuray notifications@github.com wrote: 
> 
> > Lynn, I have this at 
> > https://github.com/marshall62/mathspring/issues/132 
> > 
> > we may be duplicating here :-) 
> > 
> > On Oct 19, 2014, at 9:26 PM, lynn99 notifications@github.com wrote: 
> > 
> > > Danielle has noted this issue for all HTML problems she tested for ONR. If she clicks on Example, then clicks Done to put the example away, the original problem disappears and she never has a chance to work it. 
> > > 
> > > HTML problems make up about a third of the ONR list. Does this issue mean that we can't use them? 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub. 
> > 
> > ===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---=== 
> > Tom Murray, EdD 
> > 
> > Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 
> > 
> > University of Massachusetts Amherst 
> > 
> > Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 
> > 
> > http://www.tommurray.us (also tommurray.us@gmail.com) 
> > — 
> > Reply to this email directly or view it on GitHub. 
> > 
> > —
> > Reply to this email directly or view it on GitHub.

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 

University of Massachusetts Amherst

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

http://www.tommurray.us (also tommurray.us@gmail.com)

**Comment by lynn99** [comment]
Ah, that is what was missing. I had a shortcut to one but not the other.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
Problem Fixed by Jess
