### ISSUE TITLE
problem_209 is my guinea pig for parametrized problems

### ISSUE THREAD

**Issue by jwnewman** [perspegrity5/UMassONRMathTutorsContent#41]
Hi guys. Don't panic if you see unexplainable issues with problem_209. I've been using it it to debug my parametrization project. It's marked testable, so hopefully nothing should be harmed by this.

**Comment by jwnewman** [comment]
FYI, I just parametrized problem_830 as well. Both of these should be ready for deployment, but I have set them to testable just in case I break something as I'm developing this.

**Comment by lynn99** [comment]
Oops, 209 was recently repaired by Kevin and I had it in the pipeline to replace the online version.  Your version may have been overwritten already, not sure.

There doesn’t seem to be any way in the system to indicate when a problem is under repair.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by lynn99** [comment]
Hey Jess,

_830 is one we were planning to use in ONR.  The Flash version is not working (_630) and Ivon wants it so we were going to use _830 instead.  I’ll let you, Tom, Ivon decide whether your version is ready for the ONR trials.

_209 is not in the ONR list but a repaired version was uploaded by Tom on 10/8/14.  

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by perspegrity5** [comment]
correct!--our devel. process is very complicated!  For everything I add to the CMS we find another level of complication. 

adding repair status will take some more brainstorming.  right now that info is supposed to be in the folder system somehow. 

On Oct 28, 2014, at 1:56 PM, lynn99 notifications@github.com wrote:

> There doesn’t seem to be any way in the system to indicate when a problem is under repair. 

===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===---===
Tom Murray, EdD

Senior Research Fellow in Cognitive Tools, Educational Technology & Online Communities 

University of Massachusetts Amherst

Home: 36 Fruit Street, Northampton MA 01060; phone: is413-then-695-and-2800 

http://www.tommurray.us (also tommurray.us@gmail.com)
