### ISSUE TITLE
problem 544 is ready but has broken buttons

### ISSUE THREAD

**Issue by marshall62** [perspegrity5/UMassONRMathTutorsContent#44]
So there is definitely a bug in the CMS. I found yet another problem (544) that is set to "ready"
but has broken buttons and was turned off at some time in the past.

**Comment by lynn99** [comment]
I show this one as having had the Flash mod done.  Did these get overwritten with older copies somehow?

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by jwnewman** [comment]
To be clear, we're talking about the problem with ID 544, not problem_544. Do you have that one marked as having the flash mod done? If so, it was not pushed to git.

**Comment by lynn99** [comment]
Oh sorry, I was referring to problem_544.

I don’t have Evelyn’s Flash mod records pared with IDs, just with problem names.  So I can’t help.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by jwnewman** [comment]
Can you check your records for problem_563? Thanks!

**Comment by lynn99** [comment]
Problem_563 had the Flash mod done.  The answer buttons worked at one time.

—
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634
