### ISSUE TITLE
HTML5 Problems created--ready for ProbAuthor

### ISSUE THREAD

**Issue by perspegrity5** [perspegrity5/UMassONRMathTutorsContent#6]
May 25 from Lynn:
Last month, I uploaded about 25 HTML5 problems to the server and as far as I knew, they were ready to go.  That is how things stood at the point folks needed to turn to the classroom trials.

See list in file:
HTML problems ready for prob author (spring 2014)
https://docs.google.com/document/d/1BRIaMezwJvfuewpyyBsZxI853WIglZqxsd0kp7_V_TM/edit
 and stuff in its enclosing folder.

**Comment by lynn99** [comment]
The 8 problems for ONR Feb trials are now ready to be entered into Problem Author

**Comment by perspegrity5** [comment]
I am closing down this issue.  Stub problems have been created for all flash problems left.
